### ISSUE TITLE
Changing Backgrounds

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#10]
## Value proposition

As a user
I want to have backgrounds that change occasionally
in order to see game progression

## Description

![spring-time-sunny-day-summer-landscape-in-village-with-green-field-cloud-and-blue-sky-background-rural-countryside-with-mountain-grassland-sunlight-in-morning-nature-scenery-cartoon-background-vector](https://user-images.githubusercontent.com/105647536/234225793-0dd69906-997b-49b5-a524-704fd0779b06.jpg)

changes for example to:

![night-savannah-landscape-natural-african-background-with-hyenas-pack-silhouettes-run-through-field-with-trees-dark-starry-sky-with-full-moon-shining-game-scene-cartoon-vector-illustration_107791-9558](https://user-images.githubusercontent.com/105647536/234226672-c1be87eb-ec8f-4159-8f4d-1b2ab35718d8.jpg)

## Acceptance criteria

- [ ] have multiple backgrounds
- [ ] backgrounds change after a set number of score points

## Tasks

- [ ]implement multiple backgrounds 
- [ ] write a function that makes them change on specific score goals

Size: l
