### ISSUE TITLE
collectable objects

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#11]
## Value proposition

As a user
I want to collect coins or gems
in order to increase my score

## Description

<img width="897" alt="Bildschirmfoto 2023-04-25 um 11 08 41" src="https://user-images.githubusercontent.com/105647536/234230315-2cb46ac3-eeaf-4ced-9adc-0d78996138d0.png">

## Acceptance criteria

- [ ] coins are collectable
- [ ] coins add to the Highscore

## Tasks

- [ ] implement coin objects
- [ ] give them the function to add points to the score

Size: m
