### ISSUE TITLE
sound effects

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#12]
## Value proposition

As a user
I want to have sound effects
when the character jumps, collects objects or collides with obstacles
in order to enhance the games enjoyment

## Description

![modern-flat-design-mp3-file-icon-web-simple-style_599062-487](https://user-images.githubusercontent.com/105647536/234482836-2f923f97-8ecb-457a-8135-0b4b211a6ade.jpg)

## Acceptance criteria

- [ ] character has a jump noise
- [ ] obstacles have a hit noise
- [ ] coins have a collect noise

## Tasks

- [ ] get a sound effects library
- [ ] bind certain actions to sound effects

Size: m
