### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#14]
## Value proposition

As a user
I want that character and objects have sprites
so that I can better see what is what

## Description

<img width="211" alt="Bildschirmfoto 2023-04-26 um 08 15 49" src="https://user-images.githubusercontent.com/105647536/234485842-f1e93ed5-dbcb-4723-a5d4-1d59805a08be.png">

![pngwing com](https://user-images.githubusercontent.com/105647536/234485107-1dac6927-348e-45f1-975f-00d46581430d.png)

![228-2287658_pixel-art-maker-spikes-pixel-art png jp](https://user-images.githubusercontent.com/105647536/234486187-040089a2-e7dd-4f61-8ccd-8ae067df3e0e.jpeg)

## Acceptance criteria

- [ ] objects and character have visible sprites

## Tasks

- [ ] give the character a running man sprite
- [ ] give the obstacles sprites (spikes, stones, etc)

Size: m
