### ISSUE TITLE
animations

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#15]
## Value proposition

As a user
I want that my character has animations for running and jumping
in order to better see what I am doing and enhance the games enjoyment

## Description

![running-man-different-positions-illustration-83689473](https://user-images.githubusercontent.com/105647536/234486894-522b4ff0-1ca2-4200-b257-6c82c39c297f.jpg)

## Acceptance criteria

- [ ] running and jumping animations for the character

## Tasks

- [ ] animate a running cycle
- [ ] animate a jumping cycle

Size: l
