### ISSUE TITLE
difficulty

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#16]
## Value proposition

As a user
I want that the game gets more difficult over time
in order to feel engaged and can get better and better

## Description

<img width="952" alt="Bildschirmfoto 2023-04-26 um 08 36 57" src="https://user-images.githubusercontent.com/105647536/234490056-c8b610fa-351e-4238-a55e-f6fdd11c7da7.png">

## Acceptance criteria

- [ ] game events happen faster after reaching certain score points
- [ ] "SPEED UP!" is displayed when that happens

## Tasks

- [ ] speed up game events after reaching 1000 points, 2000 points, etc
- [ ] display a "SPEED UP!" message

Size: m
