### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#3]
## Value proposition

As a junior Developer
I want to create a endless runner game
in order to finish my next capstone project.

## Description

I  will probably use Phaser or a similar tool

## Acceptance criteria

- [ ] criteria 1: Working game functions
- [ ] criteria 2: (pending)

## Tasks

- [ ] task 1: Research possibilities and tools
- [ ] task 2: begin working on the code

Size: L(?)

**Comment by F-Kirchhoff** [comment]
Hey Alex,
please add the following changes to your user story:
- the acceptance criteria don't match the user story, please add the movement to the value proposition or remove it from the criteria
- please add the border of the screen to your wireframe so you can see where you are
- please remove the text "task 1,2" and "critera 1,2", there are only placeholders
