### ISSUE TITLE
Create Leaderboard

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#5]
## Value proposition

As a user
I want to have a leaderboard
in order to see my Highscore and compare it to others

## Description

<img width="689" alt="Bildschirmfoto 2023-04-21 um 09 52 47" src="https://user-images.githubusercontent.com/105647536/233577150-11216019-6b2f-4c99-a845-05dc71d7147f.png">

## Acceptance criteria

- [ ] My Username is shown
- [ ] My Highscore is shown

## Tasks

- [ ] Create a Highscore board
- [ ] Implement a function that takes the score and username and shows it at the score board

Size: M
