### ISSUE TITLE
Implement scores

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#6]
## Value proposition

As a User
I want to have a score
in order to see good I did in the game

## Description

<img width="955" alt="Bildschirmfoto 2023-04-21 um 10 08 56" src="https://user-images.githubusercontent.com/105647536/233580299-e142c3f9-b950-4de7-975b-9b0289f41626.png">

## Acceptance criteria

- [ ] The score is shown at the upper right corner
- [ ] the score number gets higher as the game progresses

## Tasks

- [ ] create a score counter

Size: M

**Comment by sirtobiwan** [comment]
LGTM 💪🏻 Good work.

Only one note:

The task can be a bit more detailed of how you want to create the score counter...
