### ISSUE TITLE
Character functions

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#7]
## Value proposition

As a user
I want to have a game character that can move and jump

## Description

<img width="851" alt="Bildschirmfoto 2023-04-21 um 11 20 26" src="https://user-images.githubusercontent.com/105647536/233598830-8db7c6d5-012f-4a96-a348-f5271fad45e9.png">

## Acceptance criteria

- [ ] Character can move
- [ ] Character can jump

## Tasks

- [ ] implement movement and jumping functions to the character

Size: m
