### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by Alex91w** [Alex91w/capstone-project#8]
## Value proposition

As a User
I want to have obstacles in the game
so that the character can jump and dodge them while running to enhance the game experience

## Description

<img width="901" alt="Bildschirmfoto 2023-04-24 um 12 44 38" src="https://user-images.githubusercontent.com/105647536/233974279-0db4825d-0df4-43f2-9f42-f93f92bb257c.png">

## Acceptance criteria

- [ ] having different obstacles
- [ ] obstacles interact with character (game over on touch f.e)

## Tasks

- [ ] building holes, spikes slide spaces etc
- [ ] giving those objects hit boxes

Size: L
